#! /bin/bash

## TODO Add scripts to push the changes.
##
## TODO Rename this file to slow down its rate of execution?

target_dir="$(curl -H "X-API-Key: 6SaSk9VaWyaWYja64feMzraXn7VisvMH" \
                   http://127.0.0.1:8384/rest/config |
              jp --unquoted "folders[?id == 'ybmwh-9ehdk'].path | [0]")"

git commit-changes "$target_dir" "[auto] Save synced todo items" >& ~/.syncthing_test.log
